"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var userController_1 = require("../controllers/userController");
var userRouter = (0, express_1.Router)();
userRouter.get("/", userController_1.default.getUsers);
userRouter.get("/:id", userController_1.default.getUserById);
userRouter.post("/", userController_1.default.createUser);
userRouter.put("/:id", userController_1.default.updateUser);
userRouter.delete("/:id", userController_1.default.deleteUser);
exports.default = userRouter;
